### PR TITLE
GUIDE-479: convert TextInput component to typescript + story format

### PR DESCRIPTION
**Pull request by NickDunkman**
Followed the same patterns I used in the [Radio conversion](https://github.com/aminohealth/phenotypes/pull/172)!

ezgif-5-6e0633be79

### CODE REVIEW

**Review by gelsto — APPROVED** [review]
This lgtm! I see that we hammered out this pattern nicely in the previous PR, so that context is helpful. I'm curious about if we're planning on using cavases to detail most props like this going forward, or only for a subset of components, vs. a single story where the user can customize the props to see different combinations.

**Comment by NickDunkman** [comment]
> I'm curious about if we're planning on using cavases to detail most props like this going forward, or only for a subset of components, vs. a single story where the user can customize the props to see different combinations.

@gelsto I was thinking of using this general pattern for all components -- I think it's nice to see the full capability of the component (to an extent) in the docs -- you can still click into individual stories (and the "canvas" tab) to customize props. What are your thoughts?

**Comment by gelsto** [comment]
I think the tradeoff is auto-updating vs. more detailed/complete documentation. This is kind of a weird example because a text input is very simple, but if you had props that are likely to be tweaked over time, you could rely on the story to reflect the full capability of the component without having to update the story at all.

**Comment by NickDunkman** [comment]
@gelsto Cool -- yea I think that the stuff we have in phenotypes is generally a good candidate for more thorough docs, the components we have here are more stable than usual.

**Pull request merged**
